# Site Build Settings

# jekyll-paginate configuration
paginate:            0

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: Fraternal Lodge No. 37
description: Chartered in 1844 – McDonough, Georgia
baseurl: ""
url: "https://mcdonoughmasons.github.io/mcdonoughmasons.org/"


# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
