baseurl: ""
title: "Fraternal Lodge No. 37"
email: "fraternal37fam@gmail.com"
description: "Fraternal Lodge No. 37 - Freemasons in McDonough, GA"
url: ""
theme: ""
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: "/blog/page:num/"